### ISSUE TITLE
Substance Painter 10

### ISSUE THREAD

**Issue by KrDimitrov** [jamesstringer90/Easy-GPU-PV#400]
Has anyone managed to get Substance Painter to Launch?

For me it crashes at the splash screen. Using 4090, Furmark OpenGL works, Vulkan doesnt. Im not sure if Vulkan is causing it to crash.

Here are my Substance logs...
```
[WARN] <Qt> "[DBG WARNING][Iray Service]"    0.1   GPU    rend error: NvAPI call NvAPI_GPU_GetVbiosVersionString returned an error:
[WARN] <Qt> "[DBG WARNING][Iray Service]"    0.1   GPU    rend error:   NVAPI_NOT_SUPPORTED
[WARN] <Qt> "[DBG WARNING][Iray Service]"    0.1   DYNLIB main error: Failed to load library
```

**Comment by timminator** [comment]
I've never used Substance Painter before but the NVAPI error is often resolved by creating an empty folder called "Drs" inside "C:\ProgramData\NVIDIA Corporation". Maybe this helps in your case aswell!

**Comment by KrDimitrov** [comment]
I created the folder, and saw that some files were created in it after launching Substance, but it unfortunately still crashes and the NVAPI error is still there :(  Its only a warning as well so maybe thats not whats causing the crash.. 

Thanks tho

**Comment by RafaTGG** [comment]
Try deleting the folder and recreating it, for me it worked when the error persisted after creating the folder.

**Comment by jamesstringer90** [comment]
Hey, just so you know, Easy-GPU-PV is being archived, and replaced with [App Sandbox](https://github.com/jamesstringer90/appsandbox)

It should be a lot easier to use, as it's a full app and not a collection of Powershell scripts.

And, most importantly, still completely free and open source!

Some features:

- Full App with interface for creating App Sandbox VMs
- App Sandbox runs on Windows 11 Home and Pro
- Supports creating Windows 11 or Ubuntu 26.04 LTS VMS
- Supports GPU-PV with much better support for OpenGL and better support for Vulkan
- Much better at different Language virtual machines
- Copy and Paste Support
- No need for third party game streaming apps (you can still use them though)
- Can create VMs without internet connections and they'll still work great
- Portable App, run from your Zip 
 
[Hopefully you get to try it out!](https://github.com/jamesstringer90/appsandbox/releases/tag/v0.1.0)
